language: python
python:
  - '2.7'

install:
  - pip install pyflakes pytest pytest-cov python-coveralls
  - pip install --process-dependency-links -e '.'

script:
  - pyflakes hftools
  - pytest -vv

after_success:
  - coveralls 

